name: sed-reference-basin
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - xarray
  - scipy
  - netcdf4
  - h5netcdf
  - h5py
  - geopandas
  - fiona
  - pyogrio
  - pyproj
  - shapely
  - pyshp
  - cartopy
  - matplotlib
  - psutil
  - tqdm
  - pyyaml
  - openpyxl
  - pytest
