#!/usr/bin/env python3
"""Draw reported_area basin-matching plots from spatial_match_error_table.csv.

Run after tools/explain_spatial_matching_error.py has generated its CSV outputs.

No command-line arguments are required. Edit OUTPUT_DIR below if your output path
changes, then run:

    python3 plot_reported_area_spatial_matching.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except Exception as exc:  # pragma: no cover
    raise SystemExit(f"matplotlib is required for plotting: {exc}")


# =============================================================================
# USER CONFIGURATION
# =============================================================================
# Directory generated by tools/explain_spatial_matching_error.py.
# It must contain spatial_match_error_table.csv.
OUTPUT_DIR = "/share/home/dq134/wzx/sed_data/sediment_wzx_1111/Output_r/scripts_basin_test/output/spatial_match_error_release_product"

# Input table name inside OUTPUT_DIR.
SPATIAL_MATCH_TABLE_NAME = "spatial_match_error_table.csv"

# Subdirectory for reported_area-specific figures.
REPORTED_AREA_FIGURE_SUBDIR = "figures/reported_area"

# Row-level CSV exported for the reported_area subset.
REPORTED_AREA_ROWS_CSV = "reported_area_spatial_match_rows.csv"

# If reported_area is empty, try these alternative source-area columns.
REPORTED_AREA_FALLBACK_COLUMNS = [
    "reported_area",
    "drainage_area_km2",
    "source_reported_area_km2",
    "reported_area_km2",
    "source_area_km2",
    "area_km2",
]


def clean_series(series: pd.Series) -> pd.Series:
    return series.fillna("").astype(str).str.strip().replace("", "NA")


def summarize_candidate_area_columns(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for col in REPORTED_AREA_FALLBACK_COLUMNS:
        if col not in df.columns:
            rows.append({
                "column": col,
                "exists": False,
                "positive_finite_count": 0,
                "non_missing_count": 0,
                "min_positive": np.nan,
                "max_positive": np.nan,
            })
            continue
        values = pd.to_numeric(df[col], errors="coerce").replace([np.inf, -np.inf], np.nan)
        positive = values[values > 0]
        rows.append({
            "column": col,
            "exists": True,
            "positive_finite_count": int(positive.notna().sum()),
            "non_missing_count": int(values.notna().sum()),
            "min_positive": float(positive.min()) if len(positive) else np.nan,
            "max_positive": float(positive.max()) if len(positive) else np.nan,
        })
    return pd.DataFrame(rows)


def add_reported_area_used(df: pd.DataFrame) -> pd.DataFrame:
    """Create reported_area_used from reported_area or fallback area columns."""
    out = df.copy()
    out["reported_area_used"] = np.nan
    out["reported_area_source_column"] = ""

    for col in REPORTED_AREA_FALLBACK_COLUMNS:
        if col not in out.columns:
            continue
        values = pd.to_numeric(out[col], errors="coerce").replace([np.inf, -np.inf], np.nan)
        usable = values.notna() & (values > 0)
        fill = out["reported_area_used"].isna() & usable
        out.loc[fill, "reported_area_used"] = values.loc[fill]
        out.loc[fill, "reported_area_source_column"] = col

    return out


def has_reported_area(df: pd.DataFrame) -> pd.Series:
    if "reported_area_used" not in df.columns:
        return pd.Series(False, index=df.index)
    reported = pd.to_numeric(df["reported_area_used"], errors="coerce")
    return reported.notna() & np.isfinite(reported) & (reported > 0)


def save_bar(counts: pd.Series, title: str, xlabel: str, out_png: Path) -> None:
    if counts.empty:
        return
    fig, ax = plt.subplots(figsize=(10, max(4, 0.35 * len(counts))))
    counts.sort_values().plot(kind="barh", ax=ax)
    ax.set_xlabel(xlabel)
    ax.set_title(title)
    fig.tight_layout()
    fig.savefig(out_png, dpi=180)
    plt.close(fig)


def save_share_bar(counts: pd.Series, title: str, xlabel: str, out_png: Path) -> None:
    if counts.empty:
        return
    shares = counts / counts.sum() * 100.0
    fig, ax = plt.subplots(figsize=(10, max(4, 0.35 * len(shares))))
    shares.sort_values().plot(kind="barh", ax=ax)
    ax.set_xlabel(xlabel)
    ax.set_title(title)
    fig.tight_layout()
    fig.savefig(out_png, dpi=180)
    plt.close(fig)


def save_hist(series: pd.Series, title: str, xlabel: str, out_png: Path, log_x: bool = False) -> None:
    s = pd.to_numeric(series, errors="coerce").replace([np.inf, -np.inf], np.nan).dropna()
    if log_x:
        s = s[s > 0]
    if s.empty:
        return
    bins = np.logspace(np.log10(max(s.min(), 1e-6)), np.log10(s.max()), 50) if log_x else 50
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.hist(s, bins=bins)
    if log_x:
        ax.set_xscale("log")
    ax.set_xlabel(xlabel)
    ax.set_ylabel("count")
    ax.set_title(title)
    fig.tight_layout()
    fig.savefig(out_png, dpi=180)
    plt.close(fig)


def save_scatter(df: pd.DataFrame, out_png: Path) -> None:
    needed = {"distance_m", "area_log10_error_abs"}
    if not needed.issubset(df.columns):
        return
    work = df[list(needed)].copy().replace([np.inf, -np.inf], np.nan).dropna()
    work = work[(work["distance_m"] > 0) & (work["area_log10_error_abs"] >= 0)]
    if work.empty:
        return
    fig, ax = plt.subplots(figsize=(7, 6))
    ax.scatter(work["distance_m"], work["area_log10_error_abs"], s=10, alpha=0.35)
    ax.set_xscale("log")
    ax.set_xlabel("point-to-reach distance (m, log scale)")
    ax.set_ylabel("abs(log10(MERIT area / reported area))")
    ax.set_title("Rows with reported_area: distance vs area mismatch")
    fig.tight_layout()
    fig.savefig(out_png, dpi=180)
    plt.close(fig)


def save_stacked(df: pd.DataFrame, x_col: str, stack_col: str, title: str, out_png: Path) -> None:
    if x_col not in df.columns or stack_col not in df.columns or df.empty:
        return
    pivot = pd.crosstab(clean_series(df[x_col]), clean_series(df[stack_col]))
    if pivot.empty:
        return
    fig, ax = plt.subplots(figsize=(max(8, 0.6 * len(pivot)), 5))
    pivot.plot(kind="bar", stacked=True, ax=ax)
    ax.set_xlabel(x_col)
    ax.set_ylabel("row count")
    ax.set_title(title)
    ax.legend(title=stack_col, bbox_to_anchor=(1.02, 1), loc="upper left")
    fig.tight_layout()
    fig.savefig(out_png, dpi=180)
    plt.close(fig)


def save_count_table(df: pd.DataFrame, columns: list[str], out_csv: Path) -> None:
    if df.empty:
        pd.DataFrame(columns=columns + ["row_count", "fraction", "percent"]).to_csv(out_csv, index=False)
        return

    work = df.copy()
    for col in columns:
        if col not in work.columns:
            work[col] = "NA"
        work[col] = clean_series(work[col])

    table = work.groupby(columns, dropna=False).size().reset_index(name="row_count")
    total = float(table["row_count"].sum())
    table["fraction"] = table["row_count"] / total if total else 0.0
    table["percent"] = table["fraction"] * 100.0
    table = table.sort_values("row_count", ascending=False, kind="stable")
    table.to_csv(out_csv, index=False)


def write_no_data_diagnostic(out_dir: Path, fig_dir: Path, candidate_summary: pd.DataFrame) -> None:
    diagnostic_txt = out_dir / "reported_area_no_positive_rows_diagnostic.txt"
    lines = [
        "No positive reported_area rows were found.",
        "",
        "This is why no reported_area figures were created.",
        "The plotting script only draws figures after selecting rows where reported_area_used > 0.",
        "",
        "Candidate area columns checked:",
    ]
    for row in candidate_summary.itertuples(index=False):
        lines.append(
            f"  - {row.column}: exists={row.exists}, "
            f"positive_finite_count={row.positive_finite_count}, "
            f"non_missing_count={row.non_missing_count}"
        )
    diagnostic_txt.write_text("\n".join(lines) + "\n", encoding="utf-8")

    fig, ax = plt.subplots(figsize=(9, 4))
    ax.axis("off")
    msg = (
        "No positive reported_area rows found\n\n"
        "No data-based reported_area plots were created.\n"
        "See reported_area_column_diagnostics.csv and\n"
        "reported_area_no_positive_rows_diagnostic.txt."
    )
    ax.text(0.5, 0.5, msg, ha="center", va="center", fontsize=12)
    fig.tight_layout()
    fig.savefig(fig_dir / "reported_area_no_positive_rows.png", dpi=180)
    plt.close(fig)


def main() -> int:
    out_dir = Path(OUTPUT_DIR).expanduser()
    table_path = out_dir / SPATIAL_MATCH_TABLE_NAME
    if not table_path.is_file():
        raise FileNotFoundError(
            f"Cannot find {table_path}\n"
            "Please check OUTPUT_DIR in the USER CONFIGURATION block."
        )

    df = pd.read_csv(table_path)
    candidate_summary = summarize_candidate_area_columns(df)
    candidate_summary.to_csv(out_dir / "reported_area_column_diagnostics.csv", index=False)

    df = add_reported_area_used(df)
    area_df = df[has_reported_area(df)].copy()

    fig_dir = out_dir / REPORTED_AREA_FIGURE_SUBDIR
    fig_dir.mkdir(parents=True, exist_ok=True)

    area_df.to_csv(out_dir / REPORTED_AREA_ROWS_CSV, index=False)

    if area_df.empty:
        write_no_data_diagnostic(out_dir, fig_dir, candidate_summary)
        print(f"Input table: {table_path}")
        print(f"Rows in spatial_match_error_table.csv: {len(df)}")
        print("Rows with positive reported_area_used: 0")
        print(f"Wrote area-column diagnostics -> {out_dir / 'reported_area_column_diagnostics.csv'}")
        print(f"Wrote no-data diagnostic -> {out_dir / 'reported_area_no_positive_rows_diagnostic.txt'}")
        print(f"Wrote diagnostic figure -> {fig_dir / 'reported_area_no_positive_rows.png'}")
        return 0

    save_count_table(area_df, ["reported_area_source_column"], out_dir / "reported_area_source_column_counts.csv")
    save_count_table(area_df, ["basin_status"], out_dir / "reported_area_match_status_counts.csv")
    save_count_table(area_df, ["basin_flag"], out_dir / "reported_area_match_flag_counts.csv")
    save_count_table(area_df, ["match_quality"], out_dir / "reported_area_match_quality_counts.csv")
    save_count_table(area_df, ["spatial_error_class"], out_dir / "reported_area_spatial_error_class_counts.csv")
    save_count_table(area_df, ["basin_status", "match_quality"], out_dir / "reported_area_match_status_quality_counts.csv")
    save_count_table(area_df, ["area_error_bin", "match_quality"], out_dir / "reported_area_area_error_bin_quality_counts.csv")

    if "basin_status" in area_df.columns:
        status_counts = clean_series(area_df["basin_status"]).value_counts()
        save_bar(
            status_counts,
            "Basin status among rows with reported_area",
            "row count",
            fig_dir / "reported_area_basin_status_counts.png",
        )
        save_share_bar(
            status_counts,
            "Basin status share among rows with reported_area",
            "percent of reported_area rows",
            fig_dir / "reported_area_basin_status_share.png",
        )

    if "basin_flag" in area_df.columns:
        save_bar(
            clean_series(area_df["basin_flag"]).value_counts(),
            "Basin flag among rows with reported_area",
            "row count",
            fig_dir / "reported_area_basin_flag_counts.png",
        )

    if "match_quality" in area_df.columns:
        save_bar(
            clean_series(area_df["match_quality"]).value_counts(),
            "Match quality among rows with reported_area",
            "row count",
            fig_dir / "reported_area_match_quality_counts.png",
        )

    save_bar(
        clean_series(area_df["reported_area_source_column"]).value_counts(),
        "Source column used for reported_area",
        "row count",
        fig_dir / "reported_area_source_column_counts.png",
    )

    save_hist(
        area_df.get("distance_m", pd.Series(dtype=float)),
        "Point-to-reach distance among rows with reported_area",
        "distance (m)",
        fig_dir / "reported_area_distance_hist_logx.png",
        log_x=True,
    )
    save_hist(
        area_df.get("area_log10_error_abs", pd.Series(dtype=float)),
        "Drainage-area mismatch among rows with reported_area",
        "abs(log10 area ratio)",
        fig_dir / "reported_area_area_error_hist.png",
    )
    save_scatter(area_df, fig_dir / "reported_area_distance_vs_area_error.png")
    save_stacked(
        area_df,
        "area_error_bin",
        "basin_status",
        "Basin status by drainage-area error bin",
        fig_dir / "reported_area_status_by_area_error_bin.png",
    )
    save_stacked(
        area_df,
        "match_quality",
        "basin_status",
        "Basin status by match quality for rows with reported_area",
        fig_dir / "reported_area_status_by_match_quality.png",
    )

    print(f"Input table: {table_path}")
    print(f"Rows in spatial_match_error_table.csv: {len(df)}")
    print(f"Rows with positive reported_area_used: {len(area_df)}")
    print(f"Wrote reported_area rows -> {out_dir / REPORTED_AREA_ROWS_CSV}")
    print(f"Wrote reported_area figures -> {fig_dir}")
    print(f"Wrote area-column diagnostics -> {out_dir / 'reported_area_column_diagnostics.csv'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
